theme: minima
name: "Volodya Lombrozo"
title: "Volodya Lombrozo"
author:
  name: "Volodya Lombrozo"
  email: "volodya.lombrozo@gmail.com"
encoding: utf-8
description: "The personal blog of Volodya Lombrozo"