---
name: jekyll
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  jekyll:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: bundle exec jekyll build
